### ISSUE TITLE
Test on GraalVM 21.1.0+

### ISSUE THREAD

**Issue by ppalaga** [hazelcast/quarkus-hazelcast-client#186]
Quarkus switched to 21.1.0 in their 2.0 line recently. You may want to do the same around here https://github.com/hazelcast/quarkus-hazelcast-client/blob/master/.github/workflows/build.yml#L43

**Comment by nfrankel** [comment]
Thanks for the ping @ppalaga

**Comment by ppalaga** [comment]
I came around this when discussing these failures of my colleague on Mac: https://github.com/apache/camel-quarkus/pull/2747 21.1.0 seems to be more picky about unknown classes. Does anybody of you guys use Mac and does the native compilation work for you with 21.1.0?
