### ISSUE TITLE
Upgrade to Quarkus 3 and Jakarta 9/10

### ISSUE THREAD

**Issue by ppalaga** [hazelcast/quarkus-hazelcast-client#337]
Migration tips: https://github.com/quarkiverse/quarkiverse/wiki/Migrating-to-Quarkus-3.x

**Comment by ppalaga** [comment]
@pivovarit, I wonder when we can expect some sort of an Alpha release that we could test in Camel Quarkus?

**Comment by pivovarit** [comment]
@ppalaga I'm not longer actively supporting the extension

CC @ldziedziul @frant-hartm

**Comment by ppalaga** [comment]
> @ppalaga I'm not longer actively supporting the extension

Sorry for the noise then!

**Comment by ppalaga** [comment]
@ldziedziul @frant-hartm do you guys have any plans to upgrade to Quarkus 3?

**Comment by ldziedziul** [comment]
@ppalaga we've published version 4.0.0 which works with Quarkus 3.x:  https://github.com/hazelcast/quarkus-hazelcast-client/releases/tag/v4.0.0
