### ISSUE TITLE
Extension guide at code.quarkus.io leads to nowhere

### ISSUE THREAD

**Issue by pivovarit** [hazelcast/quarkus-hazelcast-client#59]
<img width="915" alt="image" src="https://user-images.githubusercontent.com/2182533/87039543-95a22f00-c1ef-11ea-8700-df2e03a2842c.png">

**Comment by jerrinot** [comment]
There is another path to 404: When you use https://code.quarkus.io/ to generate an application with Hazelcast
It shows a pop-up:
![image](https://user-images.githubusercontent.com/158619/87160879-fb5feb00-c2c3-11ea-9217-861175f72135.png)

The Hazelcast Client Link points to https://quarkus.io/guides/hazelcast-client which returns 404.
