### ISSUE TITLE
native mode : errors when using IList, ISet, ITopic, IQueue, MultiMap, ReplicatedMap and Ringbuffer

### ISSUE THREAD

**Issue by zbendhiba** [hazelcast/quarkus-hazelcast-client#96]
**Describe the bug**
Hello, I'm working on [Hazelcast native support](https://github.com/apache/camel-quarkus/issues/1647) in [camel-quarkus](https://github.com/apache/camel-quarkus) project. I'm having some issues with execution on native mode.
When I use IMap, it works fine. But when I use IList, ISet, ITopic, IQueue, MultiMap, ReplicatedMap and Ringbuffer, it compiles fine, but I get errors on runtime.
Quarkus version / Quarkus universe BOM : 1.9.2.Final
GraalVM Version 20.2.0 (Java Version 1.8.0_262)

**Expected behavior**
I've created a [simple app](https://github.com/zbendhiba/hazelcast-quarkus-test) to show some of the problems.  I expect all of the tests in the [test class](https://github.com/zbendhiba/hazelcast-quarkus-test/blob/main/src/test/java/org/acme/resteasy/ExampleResourceTest.java) to run OK on native mode.

**To Reproduce**

1. Clone the project [hazelcast-quarkus-test](https://github.com/zbendhiba/hazelcast-quarkus-test) and run the tests on native mode, or have a Quarkus app, executing at native runtime code like.
```
ISet<Object> set = hazelcastInstance.getSet(cacheName);
BaseQueue<?> queue = hazelcastInstance.getQueue(cacheName);
Ringbuffer<Object> ringbuffer = hazelcastInstance.getRingbuffer("foo-ringbuffer");
IList<Object> list = hazelcastInstance.getList("foo-list");
ReplicatedMap<Object, Object> cache = hazelcastInstance.getReplicatedMap("foo-replicated-map");
MultiMap<Object, Object> cache = hazelcastInstance.getMultiMap("foo-multimap");
IQueue<Object> queue = hazelcastInstance.getQueue("foo-queue");
ITopic<Object> topic = hazelcastInstance.getReliableTopic("foo:topic-reliable");
 ITopic<Object> topic =  hazelcastInstance.getTopic("foo-topic");
```

**Additional context**
These are the runtime got on runtime. See full logs on the attached file.
```
org.jboss.resteasy.spi.UnhandledException: com.hazelcast.core.HazelcastException: java.lang.NoSuchMethodException: com.hazelcast.client.impl.proxy.ClientRingbufferProxy.<init>(java.lang.String, java.lang.String)
org.jboss.resteasy.spi.UnhandledException: com.hazelcast.core.HazelcastException: java.lang.NoSuchMethodException: com.hazelcast.client.impl.proxy.ClientSetProxy.<init>(java.lang.String, java.lang.String)
org.jboss.resteasy.spi.UnhandledException: com.hazelcast.core.HazelcastException: java.lang.NoSuchMethodException: com.hazelcast.client.impl.proxy.ClientReplicatedMapProxy.<init>(java.lang.String, java.lang.String)
org.jboss.resteasy.spi.UnhandledException: com.hazelcast.core.HazelcastException: java.lang.NoSuchMethodException: com.hazelcast.client.impl.proxy.ClientQueueProxy.<init>(java.lang.String, java.lang.String)
org.jboss.resteasy.spi.UnhandledException: com.hazelcast.core.HazelcastException: java.lang.NoSuchMethodException: com.hazelcast.client.impl.proxy.ClientTopicProxy.<init>(java.lang.String, java.lang.String)
org.jboss.resteasy.spi.UnhandledException: com.hazelcast.core.HazelcastException: java.lang.NoSuchMethodException: com.hazelcast.client.impl.proxy.ClientListProxy.<init>(java.lang.String, java.lang.String)


```

[logs_hazelcast_native.txt](https://github.com/hazelcast/quarkus-hazelcast-client/files/5515971/logs_hazelcast_native.txt)

**Comment by pivovarit** [comment]
Thanks for reporting! That's super useful. That's a regression, but I don't really understand yet why our IMap seems not impacted. As soon as this is fixed, will release a bugfix.

**Comment by zbendhiba** [comment]
thanks @pivovarit !!

**Comment by pivovarit** [comment]
The change is in the master already and will be released this week!

**Comment by zbendhiba** [comment]
@pivovarit  :+1:  . I'll try next week
